### ISSUE TITLE
It's not immediately obvious where to click on an event to see details

### ISSUE THREAD

**Issue by ahollenbaugh** [cdv74997/music_meet_2#15]
At the moment, we can click on the title, or the "x joined" message at the bottom. I was thinking we could either make the flyer clickable, or we could have a hyperlink that says "Details".

**Comment by ahollenbaugh** [comment]
I'm thinking of making the description (or a brief snippet of it, along with a link element that says "more") visible without having to click on "x joined" at the bottom. Also, I'm going to change "x joined" to "x comments".

**Comment by cdv74997** [comment]
This sounds like a great idea, I currently have the title clickable, I believe we can also make the flier clickable as well
